<?php

global $_LANGMAIL;
$_LANGMAIL = array();

$_LANGMAIL['Newsletter confirmation'] = 'Newsletter subscription confirmation';
$_LANGMAIL['Email verification'] = 'Potvrzení e-mailu';
$_LANGMAIL['Newsletter voucher'] = 'Odběr novinek – slevový kupón';
$_LANGMAIL['Your wishlist\\\'s link'] = 'Odkaz na Váš seznam přání';
$_LANGMAIL['Message from %1$s %2$s'] = 'Zpráva od %1$s %2$s';
$_LANGMAIL['Your cart and your discount'] = 'Nabídka slevy pro položky ve vašem košíku';
$_LANGMAIL['Thanks for your order'] = 'Děkujeme za Vaši objednávku!';
$_LANGMAIL['You are one of our best customers'] = 'Děkujeme za to, že jste jedním z našich nejlepších zákazníků';
$_LANGMAIL['We miss you'] = 'Chybíte nám';
$_LANGMAIL['Product available'] = 'Váš sledovaný produkt je nyní k dispozici';
$_LANGMAIL['Stock coverage'] = 'Pokrytí zásob';
$_LANGMAIL['Product out of stock'] = 'Produkt(y) jsou téměř vyprodané';
$_LANGMAIL['Congratulations!'] = 'Blahopřejeme!';
$_LANGMAIL['%1$s sent you a link to %2$s'] = '%1$s Vám poslal odkaz %2$s';
$_LANGMAIL['Welcome!'] = 'Dobrý den!';
$_LANGMAIL['Process the payment of your order'] = 'Zpracování Vaší platby';
$_LANGMAIL['Your message has been correctly sent #ct%1$s #tc%2$s'] = 'Vaše zpráva byla v pořádku odeslána #ct%1$s #tc%2$s';
$_LANGMAIL['Your message has been correctly sent'] = 'Vaše zpráva byla v pořádku odeslána';
$_LANGMAIL['Message from contact form'] = 'Zpráva z kontaktního formuláře';
$_LANGMAIL['New credit slip regarding your order'] = 'Nový slevový kupón k Vaší objednávce';
$_LANGMAIL['Virtual product to download'] = 'Virtuální produkt(y) k dispozici ke stažení';
$_LANGMAIL['Fwd: Customer message'] = 'Fwd: Zpráva zákazníka';
$_LANGMAIL['Your guest account has been transformed to customer account'] = 'Váš návštěvnický účet byl přeměněn na zákaznický účet.';
$_LANGMAIL['Package in transit'] = 'Zásilka na cestě';
$_LANGMAIL['Log: You have a new alert from your shop'] = 'Log: Máte nový záznam v logu z Vašeho obchodu';
$_LANGMAIL['Your order has been changed'] = 'Vaše objednávka byla změněna';
$_LANGMAIL['Order confirmation'] = 'Potvrzení objednávky';
$_LANGMAIL['Message from a customer'] = 'Zpráva od zákazníka';
$_LANGMAIL['New message regarding your order'] = 'Nová zpráva k objednávce';
$_LANGMAIL['Your order return state has changed'] = 'Stav vrácení objednávky byl změněn';
$_LANGMAIL['Your new password'] = 'Vaše nové heslo';
$_LANGMAIL['Password query confirmation'] = 'Potvrzení požadavku na nové heslo';
$_LANGMAIL['An answer to your message is available #ct%1$s #tc%2$s'] = 'Je k dispozici odpověď na vaší zprávu, #ct%1$s #tc%2$s';
$_LANGMAIL['New voucher regarding your order %s'] = 'Nový slevový kupón k vaší objednávce %s';
$_LANGMAIL['New order - #%06d'] = 'Nová objednávka – %06d';
